services:
  front-end-quasar:
    expose: 
    - 5000
    env_file: 
    - setup.env
    - ./modules/front-end-quasar/config.env
    build: ./modules/front-end-quasar/.
    ports: 
    - "9000:9000"
    volumes:
    - ./modules/front-end-quasar/backend:/backend
    - ./modules/front-end-quasar/frontend:/frontend
    depends_on:
    - knowledge-demo
    - redis
